sudo: false
language: node_js

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
    - gh-pages

env: CI=true

node_js:
  - stable

cache:
  directories:
    - node_modules

before_script:
  - npm prune

script:
  - npm run build
  - npm run test
  - npm run test:browser
  
after_success:
  - npm run coveralls
  - npm run semantic-release
